//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjEntities : DbContext
    {
        public ProjEntities()
            : base("name=ProjEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Products_group> Products_group { get; set; }
        public virtual DbSet<PGRell> PGRells { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<PFRell> PFRells { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
    }
}
